In [1]:
import pandas as pd
import pathlib

In [2]:
computed_features_folder = pathlib.Path('./new_features/')

In [43]:
small_graphs_features_files = list(computed_features_folder.glob("small*.csv"))

In [44]:
small = pd.read_csv(small_graphs_features_files[20])
small.head()

,city_name,city_id,streets_per_node_avg,node_density_km,intersection_density_km,edge_density_km,street_density_km,1way_int_count,2way_int_count,3way_int_count,4way_int_count,5way_int_count,6way_int_count,2way_int_prop,5way_int_prop,6way_int_prop,nodes_per_km_street,organic_prop,meshedness_coefficient
0,gallarate,2519,2.725128,157.734956,130.632489,37524.311736,21548.310956,772,55,3311,349,3.0,3.0,0.012241,0.000668,0.000668,0.007320,0.920009,0.623943
1,galle,8935,2.363522,219.765099,144.851462,64451.735184,32926.845488,1084,2,1949,144,1.0,0.0,0.000629,0.000314,0.000000,0.006674,0.954374,0.638797
2,galway,1584,2.264151,347.108671,216.124267,59384.942102,31204.356773,1300,14,2054,75,2.0,0.0,0.004064,0.000581,0.000000,0.011124,0.977558,0.572408
3,gama,1215,2.878424,284.709911,249.562964,66491.870863,36251.610082,1253,9,7611,1273,4.0,0.0,0.000887,0.000394,0.000000,0.007854,0.874076,0.795778
4,gamagori,12944,3.173014,143.198108,136.287366,41250.872010,21875.707928,147,3,2090,788,18.0,0.0,0.000985,0.005909,0.000000,0.006546,0.735130,1.005098

In [45]:
def merge_all_files(files_list:list) ->pd.DataFrame:
    final_df = pd.DataFrame() 
    for file in files_list:
        temp_df = pd.read_csv(file)
        final_df = pd.concat([final_df, temp_df])
    
    unwanted_cols = ['max_info_centrality', 'avg_info_centrality', 'max_betweenness_centrality',
                    'avg_betweenness_centrality', 'global_efficiency', 'avg_closeness_centrality']
    final_df.drop(unwanted_cols, axis=1, inplace=True)
    
    return final_df

In [46]:
small_graphs_feat_df = merge_all_files(small_graphs_features_files)

In [47]:
small_graphs_feat_df.head()

,city_name,city_id,streets_per_node_avg,node_density_km,intersection_density_km,edge_density_km,street_density_km,1way_int_count,2way_int_count,3way_int_count,...,11way_int_prop,12way_int_prop,13way_int_count,14way_int_count,15way_int_count,16way_int_count,13way_int_prop,14way_int_prop,15way_int_prop,16way_int_prop
0,6th of october,3881,3.074547,134.838226,129.955905,29758.680898,22894.690589,136,5,3061,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9th,4032,3.123626,50.469652,49.637735,21212.274383,19026.130382,6,1,299,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,aachen,2245,2.656357,99.808709,78.028727,30088.459591,17058.828775,896,89,2670,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,aalborg,2486,2.547955,143.889085,101.025472,33429.217757,19072.796647,1202,31,2240,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,aarhus,2518,2.620561,141.914403,104.059823,33875.790251,19395.066465,1645,57,3536,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
len(small_graphs_feat_df)

8580

In [49]:
small_graphs_feat_df.isna().sum()

city_name                     0
city_id                       0
streets_per_node_avg          0
node_density_km               0
intersection_density_km       0
edge_density_km               0
street_density_km             0
1way_int_count                0
2way_int_count                0
3way_int_count                0
4way_int_count                0
5way_int_count                0
2way_int_prop                 0
5way_int_prop                 0
nodes_per_km_street           0
organic_prop                  0
meshedness_coefficient        0
6way_int_count              300
6way_int_prop               300
7way_int_count             5060
7way_int_prop              5060
8way_int_count             7160
8way_int_prop              7160
9way_int_count             8320
9way_int_prop              8320
10way_int_count            8440
10way_int_prop             8440
11way_int_count            8520
12way_int_count            8520
11way_int_prop             8520
12way_int_prop             8520
13way_int_count            8540
14way_int_count            8540
15way_int_count            8560
16way_int_count            8560
13way_int_prop             8540
14way_int_prop             8540
15way_int_prop             8560
16way_int_prop             8560
dtype: int64

In [51]:
small_graphs_merge_file_path = pathlib.Path('./data/small_graphs_new_feats_merge.csv')
small_graphs_feat_df.to_csv(small_graphs_merge_file_path, index=False)